# Generated by Django 5.2.1 on 2025-05-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdate',
            name='exam_type',
            field=models.CharField(help_text='e.g., Mid-Semester, Internal Test 1, End-Semester', max_length=100),
        ),
    ]
