# Generated by Django 5.2.1 on 2025-05-30 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_examdate_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdate',
            name='exam_type',
            field=models.CharField(help_text='e.g., Mid-Semester Exam 1, Internal Test 2, End-Semester Exam', max_length=100),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(help_text='e.g., Diwali, Semester Break, Mid-Sem Holiday', max_length=100)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='attendance.academicsession')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('session', 'date')},
            },
        ),
    ]
