# Generated by Django 5.2.1 on 2025-05-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_examdate_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
